// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDHAzMR221A9kQh8FOqICnA6hY9LcP7Rs',
    appId: '1:457163847835:web:196e347a6f81b24629ee3e',
    messagingSenderId: '457163847835',
    projectId: 'authentication-b0fde',
    authDomain: 'authentication-b0fde.firebaseapp.com',
    storageBucket: 'authentication-b0fde.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQBfsczaJ_5w0PCYW_vR87uSWItlrY0Q',
    appId: '1:457163847835:android:d8d5ee95e8c48a2229ee3e',
    messagingSenderId: '457163847835',
    projectId: 'authentication-b0fde',
    storageBucket: 'authentication-b0fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWqX_P1Auuq4Vn_vduOxJK8AGdM--DMQ',
    appId: '1:457163847835:ios:4435574a2e8fd80b29ee3e',
    messagingSenderId: '457163847835',
    projectId: 'authentication-b0fde',
    storageBucket: 'authentication-b0fde.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmWqX_P1Auuq4Vn_vduOxJK8AGdM--DMQ',
    appId: '1:457163847835:ios:caee48b17f05cc5629ee3e',
    messagingSenderId: '457163847835',
    projectId: 'authentication-b0fde',
    storageBucket: 'authentication-b0fde.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
